### ISSUE TITLE
recyclerview.addOnScrollListener() not working properly

### ISSUE THREAD

**Issue by prashantvv** [passsy/ArrayAdapter#4]
Hello, I am using this arrayadapter with arecyclerview but the scroll listner is not working properly. Do you think it can be because of this arrayadapter. Although is is extending the RecyclerView.Adapter.
My code is -

```java
  productRecycler.addOnScrollListener(new RecyclerView.OnScrollListener() {
        @Override
        public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
          super.onScrolled(recyclerView, dx, dy);
  
        //   My dy showing only 0 & that only once when list is loaded.
         

        }
      });
```

**Comment by passsy** [comment]
Do you have enought items in your `RecyclerView` allowing it to scroll at all?

**Comment by prashantvv** [comment]
Give me 5 min. I m uploading my codes

**Comment by prashantvv** [comment]
Yes sir, I am allowing fairly 20 items in grids of 2x2.it shows all 20. But reaching at last I'm not getting any scroll listener trigger, ( OS - android 8.0 oreo). Also Im getting dy=0 at the time of list loading & after than it doesn't receiver any scroll trigger while using recycleview inside a fragment

**Comment by prashantvv** [comment]
I found that the issue was due to recycleview lying inside nestescrollview. Now working fine. Thanks anyways.

**Comment by passsy** [comment]
Thanks for asking anyways! It well help others running into the same error
